name: meetingsnoteai-app

services:
  meetingsnoteai:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: meetingsnoteai:latest
    container_name: meetingsnoteai
    ports:
      - "8080:80"
    restart: unless-stopped
